In [1]:
# Import necessary libraries 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler

import tensorflow 
from tensorflow import keras

from keras import Sequential
from keras.layers import Dense,Input

In [2]:
# Fetched this dataset from kaggle 
# The link is as below :

https://www.kaggle.com/datasets/rakeshrau/social-network-ads

In [3]:
# I have already this downloaded this dataset and have it in the same folder as this code .

In [ ]:
# We will be using three columns only to ease our evaluation
df = pd.read_csv('Social_Network_Ads.csv',usecols=['Age','EstimatedSalary','Purchased'])

In [ ]:
df.head() # Skim the head

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [8]:
# Also I found that EstimatedSalary was not on the same scale as Age (of course ) so we will normalize them both later
# using StandardScaler

In [10]:
df.shape # We have got 400 rows and three columns

(400, 3)

In [11]:
# Now lets split the dataset and normalize the X set

In [12]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [14]:
X.head() # The Independent variables

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [15]:
y.head() # The output or the dependent variable

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [17]:
scale = StandardScaler() # Instantiate the scaler and store in a variable
scale.fit(X) # Always fit first to avoid data leaks

X_scalled = scale.transform(X)

In [21]:
X_scalled[:5] # The first 5 rows now rescalled

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059]])